#!/usr/bin/env bash
#
# Rebuild the store on the Mac Mini into whichever A/B slot is not being served,
# then swap the "current" symlink and restart.
#
# The endpoint stays up for the whole load. `oxigraph load` is a writer, and
# Oxigraph documents reading a store while another process writes it as
# undefined behaviour — so the loader gets its own slot and the live server is
# never touched until the swap. Downtime is one service restart, not the length
# of a bulk load.
#
# Costs one extra store on disk (~19.4 GiB). With ~500 GB free that is free.
#
# Usage:  ./load-mini.sh /path/to/dir-with-nt-files

set -euo pipefail

SRC="${1:-.}"
BASE="${BASE:-/Users/rpage/Development/catalogue-of-life-rdf/oxigraph}"
OXIGRAPH="${OXIGRAPH:-/opt/homebrew/bin/oxigraph}"
LABEL=org.catalogueoflife.oxigraph
PLIST="/Library/LaunchDaemons/$LABEL.plist"

FILES=(taxa.nt references.nt gbif-col.nt sources.nt)

for f in "${FILES[@]}"; do
    [ -r "$SRC/$f" ] || { echo "missing: $SRC/$f  (decompress the .zst first)" >&2; exit 66; }
done

mkdir -p "$BASE"

# Work out which slot is live and pick the other one.
if [ -L "$BASE/current" ]; then
    live=$(basename "$(readlink "$BASE/current")")
else
    live=none
fi

case "$live" in
    store-a) target=store-b ;;
    *)       target=store-a ;;
esac

echo "live slot: $live  ->  loading into: $target"
echo "free before: $(df -g "$BASE" | awk 'NR==2 {print $4}') GB"

rm -rf "${BASE:?}/$target"
mkdir -p "$BASE/$target"

# Multiple -f files load in parallel, which is why this does not stream from
# compressed input — with disk to spare, parallel beats saving 10 GB.
# --lenient skips validation; these files are generated by this repo's own
# PHP scripts, not fetched from third parties.
echo "loading ~91.5M triples from ${#FILES[@]} files..."
cd "$SRC"
time "$OXIGRAPH" load --location "$BASE/$target" --lenient -f "${FILES[@]}"

echo "optimizing..."
time "$OXIGRAPH" optimize --location "$BASE/$target"

# Sanity-check the new slot BEFORE putting it live.
n=$("$OXIGRAPH" query --location "$BASE/$target" \
        --query 'SELECT (COUNT(*) AS ?n) WHERE { ?s ?p ?o }' \
        --results-format csv | tail -1)
echo "loaded triples: $n"
# taxa.nt alone is 96.3M, so this floor must stay above it or a load that
# silently dropped the other three files would still pass. Bump it whenever the
# dataset grows.
if [ "${n:-0}" -lt 110000000 ]; then
    echo "!! expected ~112.3M triples, refusing to swap. Slot left at $BASE/$target" >&2
    exit 1
fi

# Swap atomically: build the new symlink alongside, then rename over the old.
ln -sfn "$BASE/$target" "$BASE/current.new"
mv -f "$BASE/current.new" "$BASE/current"

if launchctl print "system/$LABEL" >/dev/null 2>&1; then
    echo "restarting $LABEL..."
    sudo launchctl kickstart -k "system/$LABEL"
else
    echo "service not loaded; start it with:"
    echo "  sudo launchctl bootstrap system $PLIST"
fi

du -sh "$BASE/$target"
echo "free after: $(df -g "$BASE" | awk 'NR==2 {print $4}') GB"
echo
echo "Previous slot '$live' kept as a rollback. To roll back:"
echo "  ln -sfn $BASE/$live $BASE/current.new && mv -f $BASE/current.new $BASE/current"
echo "  sudo launchctl kickstart -k system/$LABEL"
