#!/usr/bin/env bash
#
# Rebuild the Oxigraph store from N-Triples into whichever of the two slots is
# not currently being served, then swap the "current" symlink and restart.
#
# The point of the A/B slots: `oxigraph load` is a writer, and Oxigraph
# documents "opening as read-only while having an other process writing the
# database" as undefined behaviour. So loading into the live store means
# stopping the endpoint for the whole bulk load. This way it is down only for
# the restart at the end.
#
# Costs one extra store's worth of disk (~19 GB at present).
#
# Usage:  sudo ./oxigraph-load.sh /srv/col-rdf/*.nt

set -euo pipefail

BASE=/var/lib/oxigraph
SERVICE=oxigraph
OXIGRAPH=/usr/local/bin/oxigraph
OWNER=oxigraph:oxigraph

if [ $# -eq 0 ]; then
    echo "usage: $0 <file.nt> [file.nt ...]" >&2
    exit 64
fi

for f in "$@"; do
    [ -r "$f" ] || { echo "cannot read $f" >&2; exit 66; }
done

# Work out which slot is live and pick the other one.
if [ -L "$BASE/current" ]; then
    live=$(basename "$(readlink -f "$BASE/current")")
else
    live=none
fi

case "$live" in
    store-a) target=store-b ;;
    *)       target=store-a ;;
esac

echo "live slot: $live -> loading into: $target"

rm -rf "${BASE:?}/$target"
install -d -o "${OWNER%%:*}" -g "${OWNER##*:}" -m 0755 "$BASE/$target"

# --lenient skips validation for a useful speedup; these files are generated by
# this repo's own PHP scripts, not fetched from third parties.
# Multiple -f files are loaded in parallel by Oxigraph.
echo "loading $# file(s)..."
time sudo -u "${OWNER%%:*}" "$OXIGRAPH" load \
    --location "$BASE/$target" \
    --lenient \
    -f "$@"

echo "optimizing..."
time sudo -u "${OWNER%%:*}" "$OXIGRAPH" optimize --location "$BASE/$target"

# Swap atomically: create the new symlink alongside, then rename over the old.
ln -sfn "$BASE/$target" "$BASE/current.new"
mv -Tf "$BASE/current.new" "$BASE/current"
chown -h "$OWNER" "$BASE/current"

echo "restarting $SERVICE..."
systemctl restart "$SERVICE"
sleep 2
systemctl is-active --quiet "$SERVICE" && echo "ok: serving from $target"

# Smoke test through the local socket, bypassing Caddy.
curl -fsS -G http://127.0.0.1:7878/query \
    --data-urlencode 'query=SELECT (COUNT(*) AS ?n) WHERE { ?s ?p ?o }' \
    -H 'Accept: application/sparql-results+json' \
  && echo

echo
echo "Old slot '$live' left in place as a rollback. To roll back:"
echo "  ln -sfn $BASE/$live $BASE/current.new && mv -Tf $BASE/current.new $BASE/current && systemctl restart $SERVICE"
